import * as DocumentPicker from "expo-document-picker";
import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, ScrollView, Text, TextInput, TouchableOpacity, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { extractBrowserDocument } from "@/lib/browser-document-extraction";
import { getActiveRuleSet } from "@/lib/rule-set-storage";
import { saveReview } from "@/lib/review-storage";
import { SYSTEM_DEFAULT_RULE_SET, type AssignmentRuleSet } from "@/shared/rule-sets";
import { analyzeEssay } from "@/shared/essay-analysis";

const MAX_DOCUMENT_BYTES = 5_000_000;
const ACCEPTED_TYPES = ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"];

export default function ReviewEssayScreen() {
  const router = useRouter();
  const colors = useColors();
  const [title, setTitle] = useState(""); const [studentReference, setStudentReference] = useState(""); const [essayText, setEssayText] = useState(""); const [sourceName, setSourceName] = useState("Pasted text"); const [selectedName, setSelectedName] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [extracting, setExtracting] = useState(false); const [activeRuleSet, setActiveRuleSet] = useState<AssignmentRuleSet>(SYSTEM_DEFAULT_RULE_SET);
  const wordCount = useMemo(() => essayText.trim().match(/\S+/g)?.length ?? 0, [essayText]); const ready = wordCount >= 80 && !saving && !extracting;
  useFocusEffect(useCallback(() => { void getActiveRuleSet().then(setActiveRuleSet); }, []));

  const selectDocument = async () => { setError(null); const result = await DocumentPicker.getDocumentAsync({ type: ACCEPTED_TYPES, copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; const extension = asset.name.split(".").pop()?.toLowerCase(); if (extension !== "docx") { setError("Choose a DOCX file, or paste the essay text. The GitHub Pages version does not upload or process PDFs."); return; } if (asset.size && asset.size > MAX_DOCUMENT_BYTES) { setError("Choose a document smaller than 5 MB, or paste the essay text instead."); return; } try { setExtracting(true); setSelectedName(asset.name); const response = await fetch(asset.uri); const arrayBuffer = await response.arrayBuffer(); const extracted = await extractBrowserDocument(asset.name, arrayBuffer); setEssayText(extracted.text); setSourceName(asset.name); if (extracted.wordCount < 80) setError("We extracted fewer than 80 words. If the document has no selectable text, paste the essay text instead."); } catch (cause) { setSelectedName(null); setError(cause instanceof Error ? cause.message : "We could not read that document in this browser. Try pasting the essay text."); } finally { setExtracting(false); } };
  const checkMarkers = async () => { if (!ready) return; setSaving(true); try { const review = analyzeEssay(essayText, activeRuleSet); const saved = await saveReview({ ...review, title: title.trim() || sourceName.replace(/\.(pdf|docx)$/i, "") || "Untitled essay", studentReference: studentReference.trim(), sourceName, text: essayText.trim() }); router.replace({ pathname: "/findings/[id]", params: { id: saved.id } } as never); } finally { setSaving(false); } };

  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 36, width: "100%", maxWidth: 820, alignSelf: "center" }}>
    <View className="pt-3 pb-6 flex-row items-center justify-between"><TouchableOpacity onPress={() => router.back()} className="rounded-full bg-surface px-4 py-2 active:opacity-70"><Text className="text-sm font-semibold text-foreground">Cancel</Text></TouchableOpacity><Text className="text-sm font-semibold text-muted">New review</Text><View className="w-[64px]" /></View>
    <View className="gap-2"><Text className="text-3xl font-bold tracking-tight text-foreground">Check essay markers</Text><Text className="text-base leading-6 text-muted">Import a document or paste text. Essay Sentinel uses fixed rules, never an AI verdict.</Text></View>
    <View className="mt-6 rounded-3xl border border-primary bg-surface p-5"><View className="flex-row items-start justify-between gap-3"><View className="flex-1"><Text className="text-sm font-semibold text-primary">Active assignment profile</Text><Text className="mt-1 text-lg font-bold text-foreground">{activeRuleSet.name}</Text><Text className="mt-1 text-sm leading-5 text-muted">{activeRuleSet.enabledBaseRuleIds.length} baseline checks · {activeRuleSet.customPhrases.length} custom phrases</Text></View><TouchableOpacity onPress={() => router.push("/(tabs)/settings" as never)} className="rounded-xl bg-primary px-4 py-2.5 active:opacity-80"><Text className="text-sm font-semibold text-onPrimary">Change</Text></TouchableOpacity></View></View>
    <View className="mt-7 gap-5"><View className="gap-2"><Text className="text-sm font-semibold text-foreground">Essay title</Text><TextInput value={title} onChangeText={setTitle} placeholder="e.g., Climate policy response" placeholderTextColor={colors.muted} className="rounded-2xl border border-border bg-surface px-4 py-3.5 text-base text-foreground" /></View><View className="gap-2"><Text className="text-sm font-semibold text-foreground">Student reference <Text className="font-normal text-muted">(optional)</Text></Text><TextInput value={studentReference} onChangeText={setStudentReference} placeholder="e.g., Period 3 · Student 14" placeholderTextColor={colors.muted} className="rounded-2xl border border-border bg-surface px-4 py-3.5 text-base text-foreground" /></View><View className="rounded-3xl border border-border bg-surface p-5 gap-3"><View className="flex-row items-center justify-between"><View><Text className="text-base font-semibold text-foreground">Import a document</Text><Text className="mt-1 text-sm text-muted">DOCX · max 5 MB</Text></View><TouchableOpacity onPress={selectDocument} disabled={extracting} className="rounded-xl bg-primary px-4 py-2.5 active:opacity-80">{extracting ? <ActivityIndicator color={colors.onPrimary} /> : <Text className="font-semibold text-onPrimary">Choose file</Text>}</TouchableOpacity></View>{selectedName ? <Text className="text-sm font-medium text-success">Selected: {selectedName}</Text> : null}<Text className="text-xs leading-5 text-muted">DOCX is processed locally in this browser and never uploaded. For PDFs, paste the essay text below.</Text></View><View className="gap-2"><View className="flex-row items-center justify-between"><Text className="text-sm font-semibold text-foreground">Essay text</Text><Text className="text-sm text-muted">{wordCount} words</Text></View><TextInput value={essayText} onChangeText={(value) => { setEssayText(value); setSourceName("Pasted text"); }} placeholder="Paste the student submission here…" placeholderTextColor={colors.muted} multiline textAlignVertical="top" className="min-h-[260px] rounded-3xl border border-border bg-surface px-4 py-4 text-base leading-6 text-foreground" /><Text className="text-xs leading-5 text-muted">At least 80 words are needed. Markers can be wrong and are not proof of AI assistance.</Text></View></View>
    {error ? <View className="mt-5 rounded-2xl border border-warning bg-surface p-4"><Text className="text-sm leading-5 text-warning">{error}</Text></View> : null}<TouchableOpacity onPress={checkMarkers} disabled={!ready} className={`mt-7 items-center rounded-2xl py-4 ${ready ? "bg-primary active:opacity-85" : "bg-border"}`}>{saving ? <ActivityIndicator color={colors.onPrimary} /> : <Text className="text-base font-bold text-onPrimary">Check language markers</Text>}</TouchableOpacity>
  </ScrollView></ScreenContainer>;
}
